### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by soichih** [Aluxian/electron-windows-installer#10]
I am trying to test this tool by following what the README says.

When I run gulp, I get following error message.

```
hayashis@home:~/tmp$ gulp
[17:14:27] Using gulpfile ~/tmp/gulpfile.js
[17:14:27] Starting 'default'...
[17:14:27] 'default' errored after 6.49 ms
[17:14:27] Error: spawn EACCES
    at exports._errnoException (util.js:870:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at Object.exports.execFile (child_process.js:151:15)
    at /home/hayashis/tmp/node_modules/electron-windows-installer/dist/utils.js:19:17
    at Promise._execute (/home/hayashis/tmp/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/home/hayashis/tmp/node_modules/bluebird/js/release/promise.js:473:18)
    at new Promise (/home/hayashis/tmp/node_modules/bluebird/js/release/promise.js:77:14)
    at Object.module.exports.exec (/home/hayashis/tmp/node_modules/electron-windows-installer/dist/utils.js:18:12)
    at InstallerFactory.createInstaller (/home/hayashis/tmp/node_modules/electron-windows-installer/dist/index.js:115:18)
    at module.exports (/home/hayashis/tmp/node_modules/electron-windows-installer/dist/index.js:125:39)
    at Gulp.<anonymous> (/home/hayashis/tmp/gulpfile.js:5:3)
    at module.exports (/home/hayashis/tmp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/hayashis/tmp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/hayashis/tmp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/hayashis/tmp/node_modules/orchestrator/index.js:134:8)
```

I did some digging and it looks like electorn-windows-installer is running following command

```
/home/hayashis/tmp/node_modules/electron-windows-installer/vendor/nuget.exe
[ 'pack',
  '/tmp/squirrel-installer-11657-9570-layew9/kdinstall.nuspec',
  '-BasePath',
  '/home/hayashis/tmp/kdinstall-win32-x64',
  '-OutputDirectory',
  '/tmp/squirrel-installer-11657-9570-layew9',
  '-NoDefaultExcludes' ]
```

I am not sure if nuget is not installed correctly or such? I've installed wine on my laptop, but when I try to run it it fails.

```
hayashis@home:~/tmp$ wine /home/hayashis/tmp/node_modules/electron-windows-installer/vendor/nuget.exe
fixme:mscoree:get_runtime Unrecognized version L"v4.0.20926"
```

**Comment by aluxian** [comment]
This plugin has not been tested on Linux, and it's supposed to work only on Windows... But Squirrel.Windows does support Linux, so it should work (somehow) on non-Windows too.

Nuget does not need to be installed, it ships with the plugin: https://github.com/Aluxian/electron-windows-installer/tree/master/vendor

What does task `default` look like in your gulpfile?

**Comment by gp187** [comment]
Same problem here on Ubuntu 15.10

``` javascript
gulp.task('wini', function(done) {
  winInstaller({
    appDirectory: './i360-win32-x64/',
    outputDirectory: './release/',
    exe: "i360",
    setupExe: "swin",
    setupMsi: "swin",
    version: "0.1.0",
    arch: 'x64'
  }).then(done).catch(done);
});
```

and the default 

``` javascript
gulp.task('default', ['wini'], function() {
    // content
});
```

I get this error

```
[12:56:36] Starting 'wini'...
[12:56:36] 'wini' errored after 9.31 ms
[12:56:36] Error: spawn EACCES
    at exports._errnoException (util.js:873:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at exports.spawn (child_process.js:362:9)
    at Object.exports.execFile (child_process.js:151:15)
    at /lab/v6/apps/foodtech2-desktop/node_modules/electron-windows-installer/dist/utils.js:19:17
    at Promise._execute (/lab/v6/apps/foodtech2-desktop/node_modules/electron-windows-installer/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/lab/v6/apps/foodtech2-desktop/node_modules/electron-windows-installer/node_modules/bluebird/js/release/promise.js:475:18)
    at new Promise (/lab/v6/apps/foodtech2-desktop/node_modules/electron-windows-installer/node_modules/bluebird/js/release/promise.js:77:14)
    at Object.module.exports.exec (/lab/v6/apps/foodtech2-desktop/node_modules/electron-windows-installer/dist/utils.js:18:12)
    at InstallerFactory.createInstaller (/lab/v6/apps/foodtech2-desktop/node_modules/electron-windows-installer/dist/index.js:115:18)
    at module.exports (/lab/v6/apps/foodtech2-desktop/node_modules/electron-windows-installer/dist/index.js:125:39)
    at Gulp.<anonymous> (/lab/v6/apps/foodtech2-desktop/gulpfile.js:11:3)
    at module.exports (/usr/lib/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/usr/lib/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/usr/lib/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/usr/lib/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
```

**Comment by aluxian** [comment]
It doesn't work on Linux because it tries to run `Squirrel.exe` – not that this would be wrong, that's just how the module works. Your choice:
- the easy way: use a Windows machine
- the hard way: try to use Wine (not sure it'll work, Google it first so you don't waste time)
