### ISSUE TITLE
Error cannot create package

### ISSUE THREAD

**Issue by eberkund** [Aluxian/electron-windows-installer#13]
I am trying to create an installer on Windows 10 x64, I have already used electron-package to build the app but when I run the command to create an installer I get this error:

```
>  electron-installer-windows --src app-win32-x64/ --dest installers/

(node:5556) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Creating package (this may take a while)
Error: Error creating package: Error executing file (1):
C:\Users\Erik\Desktop\vue-electron\node_modules\electron-installer-windows\vendor\nuget\NuGet.exe pack C:\Users\Erik\AppData\Local\Temp\electron-116611-5556-zjk8xz.bd13hoxbt9\app_1.0.0\nuget\app.nuspec -BasePath C:\Users\Erik\AppData\Local\Temp\electron-116611-5556-zjk8xz.bd13hoxbt9\app_1.0.0\app -OutputDirectory C:\Users\Erik\AppData\Local\Temp\electron-116611-5556-zjk8xz.bd13hoxbt9\app_1.0.0\nuget -NoDefaultExcludes
The element 'metadata' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd' has incomplete content. List of possible elements expected: 'description, authors' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd'.

    at C:\Users\Erik\Desktop\vue-electron\node_modules\electron-installer-windows\src\installer.js:273:21
    at ChildProcess.<anonymous> (C:\Users\Erik\Desktop\vue-electron\node_modules\electron-installer-windows\src\installer.js:62:5)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5) 'Error: Error creating package: Error executing file (1): \nC:\\Users\\Erik\\Desktop\\vue-electron\\node_modules\\electron-installer-windows\\vendor\\nuget\\NuGet.exe pack C:\\Users\\Erik\\AppData\\Local\\Temp\\electron-116611-5556-zjk8xz.bd13hoxbt9\\app_1.0.0\\nuget\\app.nuspec -BasePath C:\\Users\\Erik\\AppData\\Local\\Temp\\electron-116611-5556-zjk8xz.bd13hoxbt9\\app_1.0.0\\app -OutputDirectory C:\\Users\\Erik\\AppData\\Local\\Temp\\electron-116611-5556-zjk8xz.bd13hoxbt9\\app_1.0.0\\nuget -NoDefaultExcludes\nThe element \'metadata\' in namespace \'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd\' has incomplete content. List of possible elements expected: \'description, authors\' in namespace \'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd\'.\r\n\n    at C:\\Users\\Erik\\Desktop\\vue-electron\\node_modules\\electron-installer-windows\\src\\installer.js:273:21\n    at ChildProcess.<anonymous> (C:\\Users\\Erik\\Desktop\\vue-electron\\node_modules\\electron-installer-windows\\src\\installer.js:62:5)\n    at emitTwo (events.js:111:20)\n    at ChildProcess.emit (events.js:191:7)\n    at maybeClose (internal/child_process.js:852:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)'

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Erik\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "installer"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.6
npm ERR! code ELIFECYCLE
npm ERR! vue-electron@3.0.0 installer: ` electron-installer-windows --src app-win32-x64/ --dest installers/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vue-electron@3.0.0 installer script ' electron-installer-windows --src app-win32-x64/ --dest installers/'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the vue-electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!      electron-installer-windows --src app-win32-x64/ --dest installers/
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs vue-electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls vue-electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Erik\Desktop\vue-electron\npm-debug.log
```

**Comment by aluxian** [comment]
What's `electron-installer-windows` in `electron-installer-windows --src app-win32-x64/ --dest installers/`? That's can't be my module. Is it a script of yours? What does it look like? I think you're missing one of the mandatory fields.
