### ISSUE TITLE
Can't create package "URI: URI"

### ISSUE THREAD

**Issue by rluisr** [Aluxian/electron-windows-installer#14]
I run `gulp create-windows-installer`, show error.
- Node.js : 6.3.1
- npm : 3.10.5
- electron-windows-installer : 1.4.2
- OS : Windows 10 x64

**Result**

```
[20:05:53] Using gulpfile ~\electron_yukari\gulpfile.js
[20:05:53] Starting 'create-windows-installer'...
[20:05:53] 'create-windows-installer' errored after 264 ms
[20:05:53] Error: Command failed: C:\Users\luis\electron_yukari\node_modules\electron-windows-installer\vendor\nuget.exe
 pack C:\Users\luis\AppData\Local\Temp\squirrel-installer-116623-8312-1lpfgz0.3xgrl1h5mi\rluisr.nuspec -BasePath C:\User
s\luis\electron_yukari\dist\app-win32-x64 -OutputDirectory C:\Users\luis\AppData\Local\Temp\squirrel-installer-116623-83
12-1lpfgz0.3xgrl1h5mi -NoDefaultExcludes
������ URI: URI �̌`���������ł��܂����ł����B

at ChildProcess.exithandler (child_process.js:202:12)
at emitTwo (events.js:106:13)
at ChildProcess.emit (events.js:191:7)
at maybeClose (internal/child_process.js:852:16)
at Process.ChildProcess._handle.onexit `(internal/child_process.js:215:5)
```

<br>

**app.js**

``` javascript
const {app, BrowserWindow, Tray, Menu, shell, autoUpdater} = require('electron');
const electron = require('electron-connect');
const client = require('cheerio-httpcli');
const CronJob = require('cron').CronJob;
const async = require('async');
const notifier = require('node-notifier');
const path = require('path');
const fs = require('fs');

let mainWindow;
let aboutWindow;
let tray;
let settings;
let old;
let contextMenu;
let menu;
let array_date = [];
let array_title = [];
let array_link = [];
let array_contents = [];

/**
 * 自動アップデート
 */
/*
autoUpdater.setFeedURL("https://c.xzy.pw/yows_notification/windows");
autoUpdater.checkForUpdates();

autoUpdater.on("update-downloaded", () => {
    index = dialog.showMessageBox({
        message: "アップデートあり",
        detail: "再起動してインストールできます。",
        buttons: ["再起動", "後で"]
    });
    if (index === 0) {
        autoUpdater.quitAndInstall();
    }
});
autoUpdater.on("update-not-available", () => {
    dialog.showMessageBox({
        message: "アップデートはありません",
        buttons: ["OK"]
    });
});
autoUpdater.on("error", () => {
    dialog.showMessageBox({
        message: "アップデートエラーが起きました",
        buttons: ["OK"]
    });
});
*/

//const url = 'http://www.tamurayukari.com/';

// start async
async.waterfall([
    /**
     * 初回起動時に設定ファイルを読み込む
     * 無かったら新規作成
     */
        function (callback) {
        fs.stat(__dirname + '/setting.json', function (error, stat) {
            if (error != null) { // File exists
                settings = fs.readFileSync(__dirname + '/settings.json', 'utf-8');
                settings = JSON.parse(settings || "null");

            } else {
                let pjson = require(__dirname + '/package.json');

                let data = {
                    version: pjson.version,
                    notification: 1
                };

                fs.writeFile(__dirname + '/settings.json', JSON.stringify(data));

                settings = fs.readFileSync(__dirname + '/settings.json', 'utf-8');
                settings = JSON.parse(settings | "null");
            }
        });

        callback(null);
    },

    /**
     * ブラウザを起動する
     */
        function startRenderer(callback) {
        app.on('ready', () => {
            tray = new Tray(__dirname + '/img/tray.png');

            contextMenu = Menu.buildFromTemplate([
                {
                    label: 'アップデートの確認', click: function () {

                }
                },
                {
                    label: 'このソフトについて', click: function () {
                    aboutWindow = new BrowserWindow({
                        height: 500,
                        width: 700,
                        resizable: false,
                        frame: false,
                        transparent: false,
                        nodeIntegration: false,
                        titleBarStyle: 'hidden' // for macOS
                    });

                    aboutWindow.loadURL('file://' + __dirname + '/about.html');

                    aboutWindow.on('closed', function () {
                        aboutWindow = null;
                    });
                }
                },
                {
                    label: '終了', click: function () {
                    app.quit();
                }
                }
            ]);

            /*
             const menu = Menu.buildFromTemplate([
             {
             label: 'YOWS Notification',
             submenu: [
             {
             label: 'このソフトについて', click: function () {
             aboutWindow = new BrowserWindow({
             height: 500,
             width: 700,
             resizable: false,
             frame: false,
             transparent: false,
             nodeIntegration: false,
             titleBarStyle: 'hidden' // for macOS
             });

             aboutWindow.loadURL('file://' + __dirname + '/about.html');

             aboutWindow.on('closed', function () {
             aboutWindow = null;
             });
             }
             },

             {
             label: '終了', click: function () {
             app.quit();
             }
             }
             ]
             }
             ]);
             */

            tray.setToolTip('YOWS Notification');
            tray.setContextMenu(contextMenu);
            //Menu.setApplicationMenu(menu);

            mainWindow = new BrowserWindow({
                height: 600,
                width: 800,
                //icon: __dirname + '/img/icon.png',
                resizable: false,
                frame: false,
                transparent: false,
                nodeIntegration: false,
                titleBarStyle: 'hidden' // for macOS
            });

            mainWindow.loadURL('file://' + __dirname + '/index.html');

            mainWindow.on('closed', function () {
                mainWindow = null;
            });

        });

        callback(null);
    },

    /**
     * ゆかりん公式サイトをスクレイピングしてタイトルと、日付を配列へ
     * @param callback null, 日付の配列, タイトルの配列
     */
        function (callback) {
        client.fetch(url, function (error, $, res) {
            let i = 0;

            /* [1] 何個お知らせが出てるか取得 */
            while (true) {
                const a = $("td a").eq(i).text();

                if (a == false) {
                    break;
                }
                i++;
            }
            /****************************/

            /* [2] 取得結果を配列にぶち込む */
            for (let x = 0; x < i; x++) {
                array_date.push($("table th").eq(x).text());
                array_title.push($("td a").eq(x).text());
                array_link.push($("table tr a").eq(x).attr("href"));
            }
            /****************************/

            callback(null);
        })
    },

    /**
     * 配列の数（お知らせの数）で、リンク先から内容を取得して
     * 配列にぶち込む
     */
        function (callback) {
        for (let i = 0; i < array_date.length; i++) {

            client.fetch(array_link[i], function (error, $, res) {
                array_contents.push($(".information_inner_single").text());
            });
        }

        callback(null, array_date, array_title);
    },

    /**
     * 取得した配列をレンダラープロセスへ
     * レンダラープロセスにプッシュする前に最新の新着データを変数に保存
     */
        function (array_date, array_title, callback) {
        mainWindow.webContents.on('did-finish-load', function () {
            old = array_title[0];

            mainWindow.webContents.send('contents_date', array_date);
            mainWindow.webContents.send('contents_title', array_title);
            mainWindow.webContents.send('contents', array_contents);
            mainWindow.webContents.send('link', array_link);
        });

        callback(null);
    },

    /**
     * 一分間にスクレイピングして変更があったら
     * レンダラープロセスを再起動
     */
        function (callback) {
        var job = new CronJob({
            cronTime: '0 */1 * * * *',
            onTick: function () {
                client.fetch(url, function (error, $, res) {
                    let now = $("td a").eq(0).text();
                    let url = $("table tr a").eq(0).attr("href");

                    /**
                     * ここから更新時のトリガー
                     */
                    if (now == old) {
                        Notification(now, url);

                        array_date.push($("table th").eq(0).text());
                        array_title.push($("td a").eq(0).text());
                        array_link.push($("table tr a").eq(0).attr("href"));

                        client.fetch(array_link[0], function (error, $, res) {
                            array_contents.push($(".information_inner_single").text());
                        });


                        mainWindow.reload();

                        mainWindow.webContents.on('did-finish-load', function () {
                            mainWindow.webContents.send('contents_date', array_date);
                            mainWindow.webContents.send('contents_title', array_title);
                            mainWindow.webContents.send('contents', array_contents);
                            mainWindow.webContents.send('link', array_link);
                        });
                    }
                });
            }
        });

        job.start();
    }
]);

function Notification(title, url) {
    notifier.notify({
        title: 'YOWS Notification',
        message: '田村ゆかり公式サイトが更新されました！\r詳しくはここをクリック！',
        //icon: path.delimiter(__dirname, '/img/icon.png'),
        wait: true,
        sound: true

    }, function (err, response) {
        // エラー処理、エラーが出た時はおれに通知しよう。
    });

    /**
     * 更新があった場合、Notifierで通知を行ってから
     * mainWindowレンダラープロセスを閉じて、再度実行させる。
     */
    notifier.on('click', function (notifierObject, options) {
        console.log("click-event");
        shell.openExternal(url);
    });

    notifier.on('timeout', function (notifierObject, options) {
        console.log("timeout-event");
        shell.openExternal(url);
    });
}
```

<br>

**index.html**

``` html
<!DOCTYPE html>
<!--suppress ALL -->
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <link href='https://fonts.googleapis.com/css?family=Passion+One:700,900,400' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="css/photon.min.css"/>
    <title>YOWS Notification</title>

    <script type="text/javascript" src="https://code.jquery.com/jquery-3.1.0.min.js"></script>

    <script type="text/javascript">
        if (typeof module === "object" && module.exports) {
            window.$ = window.jQuery = module.exports;
            module.exports = {};
        }
    </script>

    <link rel="stylesheet" href="./css/remodal.css">
    <link rel="stylesheet" href="./css/remodal-default-theme.css">
    <script src="./js/remodal.min.js"></script>

    <script type="text/javascript">
        function openWindow() {
            const inst = $('[data-remodal-id=modal]').remodal();
            inst.open();
        }
    </script>

</head>
<body>

<div class="window">
<!-- // ヘッダー // -->

    <div class="window-content">
        <div id="temp">
            <p></p>
        </div>
        <table class="table-striped">
            <thead>
            <tr>
                <th><img class="title" src="./img/title.png">&nbsp;&nbsp;&nbsp;Title</th>
                <th>Date</th>
            </tr>
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>

    <!-- // モーダルウィンドウはコ↑コ↓ // -->
    <div class="remodal" data-remodal-id="modal" data-remodal-options="hashTracking:false">
        <button data-remodal-action="close" class="remodal-close"></button>
        <h3></h3>
        <hr>
        <p></p>
        <button data-remodal-action="cancel" class="remodal-cancel">Cancel</button>
        <button data-remodal-action="confirm" class="remodal-confirm">OK</button>
    </div>
</div>

<script type="text/javascript">
    require('electron-connect').client.create();
    const ipcRenderer = require('electron').ipcRenderer;
    const {shell} = require('electron');

    let array_date = new Array();
    let array_title = new Array();
    let array_link = new Array();
    let array_contents = new Array();

    const p1 = new Promise(function (resolve, reject) {
        ipcRenderer.on('contents_date', function (event, message) {
            array_date = message;
            resolve();
        });
    });

    const p2 = new Promise(function (resolve, reject) {
        ipcRenderer.on('contents_title', function (event, message) {
            array_title = message;
            resolve();
        });
    });

    const p3 = new Promise(function (resolve, reject) {
        ipcRenderer.on('link', function (event, message) {
            array_link = message;
            resolve();
        });
    });

    const p4 = new Promise(function (resolve, reject) {
        ipcRenderer.on('contents', function (event, message) {
            array_contents = message;
            resolve();
        });
    });

    Promise.all([p1, p2, p3, p4]).then(function () {
        for (let i = 0; i < array_date.length; i++) {

            let tr = document.createElement("tr");
            tr.setAttribute("class", "contents_title");
            //tr.setAttribute("onclick", "openWindow(#contents)");

            tr.innerHTML =
                    "<td>" + array_title[i] + "</td>" +
                    "<td>" + array_date[i] + "</td>";

            const obj = document.getElementsByTagName("tbody").item(0);
            obj.appendChild(tr);
        }

        /**
         * ヘッダーの挿入
         **/
        $("div.window").prepend(
                "<header class=\"windows-header\">" +
                "<img class=\"windows-move\" src=\"./img/move.png\">" +
                "<p class=\"windows-title\" onclick=\"openYOWS('https://yukari.xzy.pw/');\">YOWS Notification</p>" +
                "<div class=\"windows-right\">" +
                "<p class=\"windows-right-contents\">NEW :<span onclick=\"openYOWS(array_link[0]);\">" + array_title[0] + "</span></p>" +
                "</div>" +
                "</header>"
        );

        /**
         * Windows と Mac の判定
         **/
        if (navigator.platform.indexOf("Win") == -1) { // Mac
            $(function() {
                //$('.windows-header').css('height', '11%');
                $('.windows-title').css('margin-top', '2%');
            });
        }

    }, function () {
        /* エラー処理 */
    });

    function openYOWS(url) {
        shell.openExternal(url);
    }

    // クリックされた要素の番号を取得して、モーダルウィンドウの中身を書き換えて表示させる
    $(document).on("click", ".contents_title", function () {
        const index = $("tr.contents_title").index(this);

        $('div.remodal > h3').text(array_title[index]);
        $('div.remodal > p').text(array_contents[index]);

        openWindow();
    });
</script>

</body>
</html>
```

**Comment by rluisr** [comment]
Sorry I didn't know adding `iconUrl` to `gulpfile.js`.
