### ISSUE TITLE
spawn mono ENOENT

### ISSUE THREAD

**Issue by reiberdatschi23** [Aluxian/electron-windows-installer#15]
Hello,

Works all fine locally on OS-X called by gulp but on Travis errors out with spawn mono ENOENT:

Unhandled rejection Error: spawn mono ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)

There's no more stack trace so I am curious where to even start looking considering it works fine on my OSX machine but fails on travis osx-machine build.

**Comment by aluxian** [comment]
Did you have to install mono specifically (on your machine)?

**Comment by aluxian** [comment]
Maybe giving https://github.com/electron/grunt-electron-installer a try would help... if that project works and mine doesn't, we'll be able to pinpoint the difference.

**Comment by reiberdatschi23** [comment]
Yes I did install wine. I can confirm also that it works as we use wine in electron-packager to switch the executables windows icon. I can't use grunt-electron-installer as we're using gulp not grunt as build system. Is there any way for better tracking the source of error?

**Comment by aluxian** [comment]
I searched my repo for `mono` and I can't find anything, so I don't know where the call to `spawn` is coming from...

**Comment by aluxian** [comment]
You could also use AppVeyor and ditch mono, it's pretty fast since their last machine upgrade (sometimes faster than my Travis builds). https://github.com/Aluxian/Whatsie/blob/master/appveyor.yml

**Comment by reiberdatschi23** [comment]
Thanks though we're bound to Travis & OSX. I have also written to Travis if they got a clue. I am even not sure why / how this mono thing is called (indirectly?) by electron-windows-installer...
