### ISSUE TITLE
XmlSchema error: Invalid end element. There are still required content items.

### ISSUE THREAD

**Issue by karolis-sh** [Aluxian/electron-windows-installer#17]
While building installer i get the following error:

`[Error: Error creating package: Error executing file (1): 
mono /home/buzzard/projects/myapp/repo/node_modules/electron-installer-windows/vendor/nuget/NuGet.exe pack /tmp/electron-11695-9485-1vsi2q7/myapp_0.2.4-test/nuget/myapp.nuspec -BasePath /tmp/electron-11695-9485-1vsi2q7/myapp_0.2.4-test/myapp -OutputDirectory /tmp/electron-11695-9485-1vsi2q7/myapp_0.2.4-test/nuget -NoDefaultExcludes
XmlSchema error: Invalid end element. There are still required content items.
] 'Error: Error creating package: Error executing file (1): \nmono /home/buzzard/projects/myapp/repo/node_modules/electron-installer-windows/vendor/nuget/NuGet.exe pack /tmp/electron-11695-9485-1vsi2q7/myapp_0.2.4-test/nuget/myapp.nuspec -BasePath /tmp/electron-11695-9485-1vsi2q7/myapp_0.2.4-test/myapp -OutputDirectory /tmp/electron-11695-9485-1vsi2q7/myapp_0.2.4-test/nuget -NoDefaultExcludes\nXmlSchema error: Invalid end element. There are still required content items.\n\n    at /home/buzzard/projects/myapp/repo/node_modules/electron-installer-windows/src/installer.js:273:21\n    at ChildProcess.<anonymous> (/home/buzzard/projects/myapp/repo/node_modules/electron-installer-windows/src/installer.js:62:5)\n    at ChildProcess.emit (events.js:117:20)\n    at maybeClose (child_process.js:766:16)\n    at Process.ChildProcess._handle.onexit (child_process.js:833:5)'
`

So the main error message is:
`XmlSchema error: Invalid end element. There are still required content items.`

Dep versions:
`"electron": "^1.3.5"`
`"electron-installer-windows": "^0.2.0"`
`"electron-packager": "^8.0.0"`

OS: ubuntu 15.04

**Comment by karolis-sh** [comment]
mixed packages `electron-windows-installer` and `electron-installer-windows`
