### ISSUE TITLE
Invalid URI format

### ISSUE THREAD

**Issue by Rafi993** [Aluxian/electron-windows-installer#18]
I am using windows 8.1 x64 and node 6.x when I tried to pack the quick start electron example I have the following error.

Invalid URI: The format of the URI could not be determined.

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

**Comment by partakit** [comment]
i have same problem. i am using windows 10

**Comment by partakit** [comment]
i resolve that.
u should add iconUrl in config params. and note that most be url.
