### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by acostela** [Aluxian/electron-windows-installer#6]
I'm getting the following error when trying to use your package. I'm using NPM3 thank you!

```
Error: spawn C:\users\acostela\myProject\node_modules\electron-windows-installer\vendor\nuget.exe ENOENT
 at exports._errnoException (util.js:849:11)
 at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
 at onErrorNT (internal/child_process.js:344:16)
 at doNTCallback2 (node.js:430:9)
 at process._tickCallback (node.js:344:17)
 at Function.Module.runMain (module.js:477:11)
 at startup (node.js:118:18)
 at node.js:952:3
```

**Comment by aluxian** [comment]
Ah, I broke this myself when I updated and I removed vendor/nuget.exe

I will add it back. For a quick fix, you can use the previous version or copy it yourself from a previous release.

-- 
Alexandru Rosianu
Full-Stack Developer
aluxian.com | startersquad.com

On 27 April 2016 at 15:54:01, acostela (notifications@github.com) wrote:

I'm getting the following error when trying to use your package. I'm using NPM3 thank you!

Error: spawn C:\users\acostela\myProject\node_modules\electron-windows-installer\vendor\nuget.exe ENOENT
 at exports._errnoException (util.js:849:11)
 at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
 at onErrorNT (internal/child_process.js:344:16)
 at doNTCallback2 (node.js:430:9)
 at process._tickCallback (node.js:344:17)
 at Function.Module.runMain (module.js:477:11)
 at startup (node.js:118:18)
 at node.js:952:3

**Comment by acostela** [comment]
Ok. Thank you very much! :+1:

**Comment by aluxian** [comment]
I've just readded the file and published a new version. This one passes the test: https://ci.appveyor.com/project/Aluxian/electron-windows-installer

I should have checked before releasing the previous (failed) release :<
