### ISSUE TITLE
Sudden error "The base package release does not exist"

### ISSUE THREAD

**Issue by vojtatranta** [Aluxian/electron-windows-installer#8]
Hi @Aluxian !
Thank your absolutely stunning work on this repo. We have been following it for long time and our whole company simply stands on it. Thanks!

But now I would like to ask for your help.
Electron windows installer worked great but now suddenly without changing anything in our build process it stopped working throwing this error:

```
 C:\a\node_modules\electron-windows-installer\vendor\Squirrel.exe --releasify C:\Users\avcd\AppData\Local\Temp\squirrel-installer-116424-8836-22vrou\avocodebeta.2.8.0-beta4.nupkg --releaseDir C:\a\release\build --loadingGif C:\a\resources\win\loading.gif --no-msi --setupIcon C:\a\resources\win\avocode.ico
System.IO.FileNotFoundException: The base package release does not exist
File name: 'C:\a\release\build\avocode-2.8.0-beta3-full.nupkg'
   at Squirrel.DeltaPackageBuilder.CreateDeltaPackage(ReleasePackage basePackage, ReleasePackage newPackage, String outputFile)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts, String baseUrl, String setupIcon, Boolean generateMsi)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
]

```

NOTE: file `avocode-2.8.0-beta3-full.nupkg` is available on our S3.

Do you have any tip for us what might caused this error? We are not able to create installer. The only real change was that we changed product name from `avocode` to `avocodebeta` and that was it. Here are our releases: https://avocode-media.s3.amazonaws.com/squirrel-windows-beta/RELEASES
And config of installer is here:

```
appDirectory: buildAppPath
    outputDirectory: path.join(releaseFolder, 'build')
    authors: 'Piffle LLC.'
    loadingGif: path.join('resources', 'win', 'loading.gif')
    setupIcon: path.join('resources', 'win', 'avocode.ico')
    iconUrl: 'https://avocode-manager.r.worldssl.net/static/images/avocode.ico'
    exe: 'Avocode.exe'
    remoteReleases: 'https://avocode-media.s3.amazonaws.com/squirrel-windows-beta/'
    noMsi: true
```

Let me know if you had any tip for us! Thanks a looot!

**Comment by vojtatranta** [comment]
Wow, strange thing. If I attempt to get .nupkg package on windows from S3 I get .zip file back, maybe thats the problem.

**Comment by vojtatranta** [comment]
UPDATE: even if I put `C:\a\release\build\avocode-2.8.0-beta3-full.nupkg` file in that path manualy I get same error.

**Comment by vojtatranta** [comment]
And if I put there `C:\a\release\build\avocode-2.8.0-beta3-full.nupkg` file manually I get this error

```
n: The file is too long. This operation is currently limited to supporting files less than 2 gigabytes in size
```

**Comment by aluxian** [comment]
Hey, I'm happy you guys at Avocode are using this! <3

I haven't encountered that before...
1. What's the command that downloads the file from S3?
2. When you copied it there yourself, did you check its size? Maybe the file was corrupted during transfer.
3. Are you running the build process on a CI, VM or local machine?

**Comment by aluxian** [comment]
P.S. Have you tried reverting the product name to `avocode` and testing if it works? If you had, we'd have known for sure that that's the culprit. Otherwise, I don't think it's worth trying right now, it's already pretty obvious that's the problem since that's the only thing you changed.

**Comment by vojtatranta** [comment]
@Aluxian We are happy to use it.
I managed to create a build. Thing was that  I tried to create build with version that was already built an presented in RELEASES.
When I bumped version it worked. But still I can't create build with older version.
I tried to revert product name too, no luck.
1. there's no command we just put URL as parameter of `remoteReleases`
2. size is around 3megs
3. it's local

**Comment by aluxian** [comment]
So it works now? What do you mean you still can't create a build with older version?

**Comment by vojtatranta** [comment]
I already have build of version let's say `2.4` which is already in RELEASES. This bugs occurs when I tried to create build with version `2.4` again. But If I bump version to `2.5` it works.
If I create build with `2.3` it fails the same way as `2.4`

**Comment by aluxian** [comment]
Oooh. I think I _might_ have encountered this myself as well. I also wanted to build a version that was already in the RELEASES file. But that's the only time I tried to build an already released version, so that's why in all the other cases I did not encounter your error.

Now, why would you want to build versions that are already released?

**Comment by vojtatranta** [comment]
Mostly for testing purposes, whether auto update works

**Comment by aluxian** [comment]
In that case, I think the easiest way would be to use a custom RELEASES file for testing.

**Comment by aluxian** [comment]
And about the bug itself, I think that's a bug in Squirrel.Windows. I did a quick search through its issues but I couldn't find anything related.

**Comment by vojtatranta** [comment]
Yup, might be good idea. I just noticed that this question was not answered on the internet.
Yup yup, I haven't found anything too.

**Comment by aluxian** [comment]
I submitted an issue upstream ^
